name: Build Helm Chart

on:
  push:
    tags: '*'
  workflow_dispatch:

jobs:
  build_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:    
    - name: Set version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Publish Release Helm charts
      uses: stefanprodan/helm-gh-pages@master
      with:
        token: ${{ github.token }}
        charts_dir: "./charts"
        target_dir: "./helm-charts"
        chart_version: $RELEASE_VERSION
